vpn_server_name: "infovpn"
vpn_key_name: "serverVPN"
vpn_key_country: "EU"
vpn_key_province: "FR"
vpn_key_city: "Paris"
vpn_key_org: "popov"
vpn_key_email: "megevand.alexis@gmail.com"
vpn_key_ou: "po"