- name: Update apt packages
  ansible.builtin.apt:
    upgrade: true
    cache_valid_time: 3600

- name: Install openvpn
  ansible.builtin.apt:
    name: openvpn,easy-rsa,iptables-persistent
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Check if ca dir already.stat.exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/openvpn-ca/"
  register: __check_openvpn_ca_dir_present

- name: Create CA dir
  ansible.builtin.command: "make-cadir {{ ansible_env.HOME }}/openvpn-ca"
  when: __check_openvpn_ca_dir_present.stat.exists == false

- name: Customize CA variable configuration
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/openvpn-ca/vars"
    regexp: "^{{ item.property | regex_escape() }}="
    line: "{{ item.property }}={{ item.value }}"
  loop:
    - { property: 'export KEY_NAME', value: '{{ vpn_key_name }}' }
    - { property: 'export KEY_COUNTRY', value: '{{ vpn_key_country }}' }
    - { property: 'export KEY_PROVINCE', value: '{{ vpn_key_province }}' }
    - { property: 'export KEY_CITY', value: '{{ vpn_key_city }}' }
    - { property: 'export KEY_ORG', value: '{{ vpn_key_org }}' }
    - { property: 'export KEY_EMAIL', value: '{{ vpn_key_email }}' }
    - { property: 'export KEY_OU', value: '{{ vpn_key_ou }}' }
    - { property: 'export KEY_CONFIG', value: '{{ ansible_env.HOME }}/openvpn-ca/openssl-1.1.1.cnf' }
    - { property: 'export KEY_DIR', value: '{{ ansible_env.HOME }}/openvpn-ca/keys' }

- name: check if ca file already.stat.exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/openvpn-ca/pki/ca.crt"
  register: __check_openvpn_ca_crt_file_present

- name: build the certificate authority
  ansible.builtin.shell: >
    ./easyrsa init-pki;
    ./easyrsa --batch --req-cn="cn_{{ vpn_server_name }}" build-ca nopass;
  args:
    chdir: "{{ ansible_env.HOME }}/openvpn-ca/"
    executable: /bin/bash
  when: __check_openvpn_ca_crt_file_present.stat.exists == false

- name: check if crl server file already.stat.exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/openvpn-ca/pki/crl.pem"
  register: __check_openvpn_crl_server_crt_file_present

- name: build crl and server certificate
  ansible.builtin.shell: >
    ./easyrsa --batch build-server-full "server_{{ vpn_server_name }}" nopass;
    EASYRSA_CRL_DAYS=3650 ./easyrsa gen-crl;
  args:
    chdir: "{{ ansible_env.HOME }}/openvpn-ca/"
    executable: /bin/bash
  when: __check_openvpn_crl_server_crt_file_present.stat.exists == false



